//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework03.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework03.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42 Place.
        /// </summary>
        public static string DiscText01 {
            get {
                return ResourceManager.GetString("DiscText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Place.
        /// </summary>
        public static string DiscText02 {
            get {
                return ResourceManager.GetString("DiscText02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28 Place.
        /// </summary>
        public static string DiscText03 {
            get {
                return ResourceManager.GetString("DiscText03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34 Place.
        /// </summary>
        public static string DiscText04 {
            get {
                return ResourceManager.GetString("DiscText04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29 Place.
        /// </summary>
        public static string DiscText05 {
            get {
                return ResourceManager.GetString("DiscText05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 Place.
        /// </summary>
        public static string DiscText06 {
            get {
                return ResourceManager.GetString("DiscText06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar &amp; Hotels.
        /// </summary>
        public static string DiscTitle01 {
            get {
                return ResourceManager.GetString("DiscTitle01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Dining.
        /// </summary>
        public static string DiscTitle02 {
            get {
                return ResourceManager.GetString("DiscTitle02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafes.
        /// </summary>
        public static string DiscTitle03 {
            get {
                return ResourceManager.GetString("DiscTitle03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby.
        /// </summary>
        public static string DiscTitle04 {
            get {
                return ResourceManager.GetString("DiscTitle04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Foods.
        /// </summary>
        public static string DiscTitle05 {
            get {
                return ResourceManager.GetString("DiscTitle05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Foods.
        /// </summary>
        public static string DiscTitle06 {
            get {
                return ResourceManager.GetString("DiscTitle06", resourceCulture);
            }
        }
    }
}
